; Name: [Doyun GU]
; UID:  [11095970]

    processor 18F8722
    config OSC=HS, WDT=OFF, LVP=OFF
    radix decimal
    org 0x00
    
    ; Main Code
    
LATA equ 0xF89 
TRISA equ 0xF92
PORTA equ 0xF80
LATB equ 0xF8A 
TRISB equ 0xF93 
PORTB equ 0xF81
LATC equ 0xF8B 
TRISC equ 0xF94 
PORTC equ 0xF82
LATF equ 0xF8E
TRISF equ 0xF97 
PORTF equ 0xF85
LATH equ 0xF90 
TRISH equ 0xF99 
PORTH equ 0xF87
LATJ equ 0xF91 
TRISJ equ 0xF9A 
PORTJ equ 0xF88
ADCON1 equ 0xFC1
 
    ; SETUP LEDs
    MOVLW 0
    MOVWF TRISF    ; SET LEDs AS OUTPUT
    
    ; SETUP TRANSISTORS
    
    ; Q1 AND Q2
    MOVLW B'11111100'
    MOVWF TRISH    ; SET RH0 & RH1 AS OUTPUT
    
    ; Q3
    MOVLW B'11101111'
    MOVWF TRISA    ; SET RA4 AS OUTPUT
    
; MAIN LOOP STARTS
L_MAIN
    ; CALL SWITCHES
    CALL SWITCHES
    
    ; PATTERN FOR LEDs
    MOVLW B'11111111'
    MOVWF LATF
    
    ; TURN OFF Q1 AND Q2 TRANSISTORS
    MOVLW B'11111111'
    MOVWF LATH
    
    ; TURN ON Q3 TRANSISTOR
    MOVLW B'00010000'
    MOVWF LATA
    
    ; CALL DELAYS
    ; DELAY 1: DELAY BEFORE LEDs OFF
    ; IF STATEMENT_PB2 IS PRESSED (1)/PB2 IS NOT PRESSED (0)
    BTFSS SWITCHES, 5    ; PRESSED(0): CONTINUE, NOT PRESSED(1): SKIP
    
    ; BTFSS-CASE 1: PRESSED
    CALL SUB_400ms
    
    ; BTFSS-CASE 2: NOT PRESSED
    BTFSC SWITCHES, 5    ; PRESSED (0): SKIP, NOT PRESSED(1): CONTINUE
    
    ; BTFSC-CASE 1: NOT PRESSED
    CALL SUB_40ms
    
    ; BTFSC-CASE 2: PRESSED
    ; TURN OFF Q3 TRANSISTOR
    MOVLW B'00000000'
    MOVWF LATA
    
    ; DELAY 2: DELAY AFTER LEDs OFF
    BTFSS SWITCHES, 5    ; PRESSED(0): CONTINUE, NOT PRESSED(1): SKIP
    
    ; BTFSS-CASE 1: PRESSED
    CALL SUB_400ms
    
    ; BTFSC-CASE 2: NOT PRESSED
    BTFSC SWITCHES, 5    ; PRESSED (0): SKIP, NOT PRESSED(1): CONTINUE
    
    ; BTFSC- CASE 1: NOT PRESSED
    CALL SUB_40ms        
    
    ; BTFSC-CASE 2: PRESSED
    BRA L_MAIN
