; Name: [Doyun GU]
; UID:  [11095970]

    processor 18F8722
    config OSC=HS, WDT=OFF, LVP=OFF
    radix decimal
    org 0x00
    
LATA equ 0xF89 
TRISA equ 0xF92 
PORTA equ 0xF80
LATB equ 0xF8A 
TRISB equ 0xF93 
PORTB equ 0xF81
LATC equ 0xF8B 
TRISC equ 0xF94 
PORTC equ 0xF82
LATF equ 0xF8E 
TRISF equ 0xF97 
PORTF equ 0xF85
LATH equ 0xF90 
TRISH equ 0xF99 
PORTH equ 0xF87
LATJ equ 0xF91 
TRISJ equ 0xF9A 
PORTJ equ 0xF88
ADCON1 equ 0xFC1


; THE TRISTATES
    MOVLW B'00100000'    ; PB1
    MOVWF TRISJ
   
    MOVLW B'11111100'    ; TRANSISTOR Q2
    MOVWF TRISH
   
    MOVLW B'11101111'    ; TRANSISTOR Q3
    MOVWF TRISA
   
    MOVLW B'00011100'    ; SWITCHES 1-3 RC2-4
    MOVWF TRISC
   
    MOVLW B'00000000'    ; LEDs
    MOVWF TRISF
    
    MOVLW 0X0F           ; ANALOGUE TO DIGITAL INPUT
    MOVWF ADCON1
   
L_MAIN
    NOP
    ;START OF PART 1
    MOVLW B'11011111'    ; SETTING THE VALUE OF PB1 TO LOW SO IT ACTIVATES WHEN PUSHED DOWN
    MOVWF LATJ
   
    MOVF PORTJ, W        ; READING THE VALUE OF PB1 AND STORING INPUT
    MOVWF 0X00
   
    BTFSC 0X00, 5        ; IF STATEMENT FOR CODE TO EXECUTE IF BIT 5 IS 0
    BRA Conduction_not_filled
    
    MOVLW B'10000101'    ; MASKING THE INPUT FROM PB1 TO DISPLAY A "U" WHEN PUSHED
    ANDWF 0X00
    
    MOVLW B'00000000'    ; TURNING OFF TRANSISTOR Q3
    MOVWF LATA
    
    MOVLW B'11111111'
    MOVWF LATF           ; MASKING SURE THAT ALL SEGMENTS ARE OFF
    
    MOVLW B'11111101'    ; SETTING VALUE OF TRANSISTOR Q2 TO LOW TO TURN ON
    MOVWF LATH
    
    MOVF 0X00, W         ; BRINGING THE VALUE FROM PB1 TO LEDs
    MOVWF LATF
    
    MOVLW B'11111111'    ; SETTING TRANSISTOR Q2 AS OUTPUT TO TURN OFF
    MOVWF LATH
    
    MOVLW B'11111111'    ; TURNING OFF THE PB1
    MOVWF LATJ
    
Conduction_not_filled    ; CODE MOVES HERE WHEN THE PB1 IS NOT PUSHED
    
    ; START OF PART 2
    MOVLW B'11111111'    ; SETTING TRANSISTOR Q2 AS OUTPUT TO TURN OFF
    MOVWF LATH
    
    MOVLW B'00000000'    ; CLEARING WHATEVER IN F
    MOVWF LATF
    
    MOVLW B'00010000'    ; TURNING ON TRANSISTOR Q3 BY SETTING IT TO HIGH
    MOVWF LATA
    
    MOVF PORTC, W        ; MOVING THE INPUT OF SWITCHES TO WREG 
    MOVWF 0X02           ; SHIFTING THE VALUE OF SWITCHES 1-3 TO THE 2 TO THE RIGHT TO BE DISPLAYED AS THE RIGHTMOST LEDs
    
    RRNCF 0X02, F
    RRNCF 0X02, W
    ANDLW B'00000111'    ; MAKING THE INPUT OF THE SWITCHES SO ONLY 1-3 ARE INPUTS
    MOVWF LATF
    
    ; END OF PART 2
    ; START OF PART 3 AND PART 4: SAVING THAT VALUE INTO BANK1
    
    MOVLB 0X1             ; ALLOWS ACCESS TO BANK 1
    MOVF PORTH, W         ; READING AVLUE FROM SWITCHES 8-5
    ANDLW B'11110000'     ; MASKING THESE VALUES TO ONLY READ THESE 4 SWITCHES
    MOVWF 0X01, 1
    IORWF 0X02, F         ; PUTTING THE VALUE FROM SWTICHES INTO ASSIGNED MEMORY (0x02)
    MOVWF LATF            ; DISPLAY THE RESULT ON THE LEDs
    NOP
    
    ; PART 5
    MOVF 0X101, W
    
    ; CHECK THAT NUMBER IS POSITIVE
    
    BTFSC 0X101, 7         ; IF STATEMENT FOR CODE TO EXECUTE IF BIT 7 IS 0
    BRA NUMBER_IS_NEGATIVE
    
    ;ROTATE THE NUMBER 4 TIMES
    RRNCF 0X101, F
    RRNCF 0X101, F
    RRNCF 0X101, F
    RRNCF 0X101, W
    
    ; SEE IF THE TEH NUMBER IS BIGGER THAN 5
    
    SUBLW 5
    BN BIGGER_THAN_5
    BRA SMALLER_THAN_5
    
BIGGER_THAN_5    ; CONDITION IS MET
    MOVLW B'00000000'      ; TURNING OFF TRANSISTOR Q3
    MOVWF LATA
    
    MOVLW B'00000110'
    MOVWF LATF
    
    MOVLW B'11111110'      ; SETTING TRANSISTOR Q2 AS OUTPUT TO TURN OFF
    MOVWF LATH
    
SMALLER_THAN_5
NUMBER_IS_NEGATIVE
    BRA L_MAIN
    
    end
