; Name: [Doyun GU]
; UID:  [11095970]
    
    processor 18F8722
    config OSC=HS, WDT=OFF, LVP=OFF
    radix decimal
    org 0x00
    
LATA equ 0xF89 
TRISA equ 0xF92 
PORTA equ 0xF80
LATB equ 0xF8A 
TRISB equ 0xF93 
PORTB equ 0xF81
LATC equ 0xF8B 
TRISC equ 0xF94 
PORTC equ 0xF82
LATF equ 0xF8E 
TRISF equ 0xF97 
PORTF equ 0xF85
LATH equ 0xF90 
TRISH equ 0xF99 
PORTH equ 0xF87
LATJ equ 0xF91 
TRISJ equ 0xF9A 
PORTJ equ 0xF88
ADCON1 equ 0xFC1

L_MAIN
   
   NOP
   MOVLW 0x0F          ; CHANGING SWITCHES FROM ANALOGUE TO DIGITAL INPUT
   MOVWF ADCON1
   
   ; Start of PART 1
   MOVLW B'00100000'   ; MAKING PB1 AS AN INPUT
   MOVWF TRISJ
   
   MOVLW B'11011111'   ; SETTING THE VALUE OF PB1 TO LOW SO IT ACTIVATES WHEN PUSHED DOWN
   MOVWF LATJ
   
   MOVF PORTJ, W       ; READING THE VALUE OF PB1 AND STORING IT
   MOVWF 0x00
   
   BTFSS 0x00, 5       ; IF STATEMENT FOR CODE TO EXECUTE
   
   MOVLW B'10000101'   ; MASKING THE INPUT FROM PB1 TO DISPLAY A "U" WHEN PUSHED
   ANDWF 0x00
    
   MOVLW B'11111111'   ; TURNING ON ALL LEDs
   MOVWF LATF
   
   MOVLW B'11111101'   ; SETTING TRANSISTOR Q2 AS OUTPUT
   MOVWF TRISH
   
   MOVLW B'11111101'    ; SETTING VALUE OF TRANSISTOR Q2 TO LOW TO TURN ON
   MOVWF LATH
   
   MOVLW B'00000000'    ; SETTING ALL OF LEDs AS OUTPUTS
   MOVWF TRISF
   
   MOVF 0X00, W         ; BRINGING THE VALUE FROM PB1 TO LEDs
   MOVWF LATF
   
   ; End of Part 1
   
   MOVLW B'11111111'    ; TURNING OFF Q2 BY SETTING IT TO INPUT
   MOVWF TRISH
   
   MOVLW B'00000000'    ; SETTING ALL LEDs TO LOW TO TURN THEM OFF
   MOVWF LATF
   
   ; Start of Part 2
   
   MOVLW B'11101111'   ; SETTING VALUE OF TRANSISTOR Q2 TO LOW TO TURN ON
   MOVWF TRISA
   
   MOVLW B'00010000'   ; SETTING ALL OF LEDs AS OUTPUTS
   MOVWF LATA
   
   MOVLW B'00011100'   ; SETTING SWITHCES 1-3 AS INPUTS
   MOVWF TRISC
   
   MOVF PORTC, W       ; MOVING THE INPUT OF SWITCHES TO WREG
   
   MOVWF 0x02          ; SHIFTING THE VALUES OF SWITCHES 1-3 TO THE 2 TO THE RIGHT TO BE DISPLAYED AS THE RIGHT MOST LEDs
   RRNCF 0x02, F
   RRNCF 0x02, W
   ANDLW B'00000111'   ; MASKING THE INPUT OF THE SWITCHES SO ONLY 1-3 ARE INPUTS
   MOVWF LATF
   
   MOVLW B'11111111'   ; TURNING OFF TRANSISTORS Q3 BY SETTING IT TO INPUT
   MOVWF TRISA
   
   ; End of Part 2
   
   BRA L_MAIN
   
   end
   
